spring:
  application:
    name: "HangBook-Market"
  datasource:
    url: jdbc:h2:tcp://localhost/~/hangbook-market;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 ?? ?? ??
