spring:
  application:
    name: "HangBook-Market"
  datasource:
    url: jdbc:h2:tcp://localhost/~/hangbook-market  # H2? ??? DB ??
    driver-class-name: org.h2.Driver
    username: sa
    password: 1
  h2:
    console:
      enabled: true  # H2 ??? ??? (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: create-drop  # ??? ?? ???? (create, update, validate, none ? ?? ??)
    show-sql: true      # ???? SQL ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 ?? ?? ??
